AWSTemplateFormatVersion: '2010-09-09'
Description: "Standalone MongoDB server"
Parameters:
  VpcName:
    Type: String
  ZoneName:
    Type: String
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  MongoDB:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0c6b1d09930fac512"
      InstanceType: "t2.micro"
      KeyName:
        Ref: KeyName
      SubnetId: {'Fn::ImportValue': !Sub '${VpcName}-DBSubnet-${ZoneName}'}
      SecurityGroupIds: [{'Fn::ImportValue': !Sub '${VpcName}-sg-alltraffic'}]
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash
                #setting up the repo for mongodb
                touch /etc/yum.repos.d/mongodb-org-4.0.repo
                echo '[mongodb-org-4.0]' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                echo 'name=MongoDB Repository' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                echo 'baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.0/x86_64/' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                echo 'gpgcheck=1' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                echo 'enabled=1' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                echo 'gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc' >> /etc/yum.repos.d/mongodb-org-4.0.repo
                #installing mongodb service
                yum install -y mongodb-org
                service mongod start
                chkconfig mongod on
                #replacing the bindIP for mongodb
                sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
                service mongod restart
                #login to mongodb and creating the balance collection and initial balance entry
                mongo << EOF
                use personal_banking
                db.createCollection("balances");
                db.balances.insert({    myId: '<emailaddress>',     myAccountBalance: '100000', });
                exit
                EOF
      Tags:
      - Key: Name
        Value: !Sub '${VpcName}-MongoDB'
Outputs:
  DBEc2IP:
    Description: "IP address of the MongoDB server"
    Value: !GetAtt "MongoDB.PublicIp"
    Export:
      Name:
        !Sub '${VpcName}-MongoDB-IP-Address'
