AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcName:
    Type: String
  ZoneName:
    Type: String
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  DockerBuildHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0c6b1d09930fac512"
      InstanceType: "t2.micro"
      KeyName:
        Ref: KeyName
      SubnetId: {'Fn::ImportValue': !Sub '${VpcName}-WebSubnet-${ZoneName}'}
      SecurityGroupIds: [{'Fn::ImportValue': !Sub '${VpcName}-sg-alltraffic'}]
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash
                #setting up variables for nvm installation in bashrc
                echo 'export NVM_DIR="/.nvm"' >> ~/.bashrc
                echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc
                source ~/.bashrc
                #downloading nvm installation scripts
                curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
                #purposely need to reload nvm.sh as the above install.sh exits with an error and nvm.sh does not run
                source /.nvm/nvm.sh
                #installing nodejs
                nvm install 8.9
                node -e "console.log('Running Node.js ' + process.version)"
                #Installing git & Docker
                yum install -y git
                amazon-linux-extras install docker
                service docker start
                chkconfig docker on
                usermod -a -G docker ec2-user
                #download the master code for all API microservices
                cd /home/ec2-user
                git clone https://github.com/thecloudgarage/vuejs-inb.git
                mkdir -p vuejs-client
                mv /home/ec2-user/vuejs-inb/vuejs-client/* /home/ec2-user/vuejs-client/
                cd /home/ec2-user/vuejs-client/
                sed -i 's/ApiHostBalance/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostFeedback/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostForgot/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostLogin/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostPassword/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostPayee/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostReset/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostTransfer/'nodejsmodulithapiserver'/g' webpack.prod.js
                sed -i 's/ApiHostUser/'nodejsmodulithapiserver'/g' webpack.prod.js
                npm install
                npm run build-prod
                #create the Dockerfile for user API and write the Dockerfile contents via echo commands
                touch Dockerfile
                echo 'FROM httpd:2.4' >> Dockerfile
                echo 'COPY ./dist/ /usr/local/apache2/htdocs/' >> Dockerfile
                docker build -t vuejs-modulith-client .
                #now tag the images for docker hub uploads (note I am providing my docker hub registry name)
                docker tag vuejs-modulith-client thecloudgarage/vuejs-modulith-client
                #later, via SSH login to docker hub and push the images :)
      Tags:
      - Key: Name
        Value: !Sub '${VpcName}-Docker-VueJS-Modulith-Client'
Outputs:
  AppEc2IP:
    Description: "IP address of the Docker Build Host"
    Value: !GetAtt "DockerBuildHost.PublicIp"
    Export:
      Name:
        !Sub "${VpcName}-Docker-VueJS-Client"
